# Generated by Django 3.2.12 on 2022-07-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0016_postrevision_ip_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='can_post_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='can_post_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='can_post_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_tag_filter_strategy',
            field=models.SmallIntegerField(choices=[(0, 'all tags'), (1, 'exclude ignored tags'), (2, 'only interesting tags'), (3, 'only subscribed tags')], default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_tag_filter_strategy',
            field=models.SmallIntegerField(choices=[(0, 'all tags'), (1, 'exclude ignored tags'), (2, 'only interesting tags'), (3, 'only subscribed tags')], default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('d', 'administrator'), ('m', 'moderator'), ('a', 'approved'), ('w', 'watched'), ('s', 'suspended'), ('b', 'blocked'), ('t', 'terminated')], db_index=True, default='w', max_length=2),
        ),
    ]
